### ISSUE TITLE
Username / password for the admin panel

### ISSUE THREAD

**Issue by thangchung** [xonaki/NetCoreCMS#5]
I think it will be good for the audiences if you can put the default username/password somewhere in the README or in the login panel.

**Comment by masums** [comment]
Thank you for your comment. Actually, default role is Admin. So if anyone register he will be able to see admin panel. Still, we appreciate your suggestion. We will add username and password.

**Comment by thangchung** [comment]
Okay. Glad to see your project grows up very fast with features.
