### ISSUE TITLE
Wrong Rout after finish instalation

### ISSUE THREAD

**Issue by eduardoguilarducci** [xonaki/NetCoreCMS#9]
When I Finish the instalation (CreateAdmin), the app is redirected to /CmsHome, and return 404 error (Not Found)
*Database is created,  including tables and registers.

<img width="1029" alt="screen shot 2018-01-30 at 23 14 43" src="https://user-images.githubusercontent.com/1053355/35600133-83f7eb22-0613-11e8-80eb-b1640fd3612d.png">

What Im doing wrong?

**Comment by masums** [comment]
Which database version you have used? Ncc requires MySql 5.6 or above. Also if you want to test multi-language then you have to choose Database charset ucs2 and Database collection ucs2_unicode_ci.
After installation complete, it restarts the site for that reason takes some time to be ready. If you still fetch any problem then see the log file at __Logs folder there you will find exact error.

Thank you

**Comment by gmnazmul** [comment]
Please Build the full solution before running the web project.

**Comment by eduardoguilarducci** [comment]
Its MySQL database, and instalation works fine. 

The error was in setup.json points the default route to /HomeCMS, but the correct rout should be /Home/HomeCMS.

Changing this, everything worked.

**Comment by masums** [comment]
Ok, thank you for using NetCoreCMS. Closing this issue.
